### ISSUE TITLE
Issue on Terraform Install Terraform Phase

### ISSUE THREAD

**Issue by peppardo23** [brokedba/terraform-examples#5]
Hi, 
I'm facing an issue on the configuration of Terraform DevOps OCI project. In the specific I'm trying to use the files under oci_devops_policy_dg_terraform folder.
"build_spec.yaml" file contains the build pipeline specification with a "Install Terraform" step that may install the newer version of Terraform inside pipeline worker, but the current behavious is: 
1. Worker start
2. Install Terraform step made the installation of yum-utils and terraform and these operations are confirmed via logs. Terraform 1.6  is installed in pipeline worker.
3. TENANCY - Terraform actions step launch several terraform commands, but from the logs are visible that these command are executed with an older version of terraform (1.2) probably pre-installed inside pipeline worker.

Why I'm not able to use new version of terraform for my pipeline?

Let me write some other informations about my environment. I'm actually working inside OCI tenant in Frankfurt region, here is available only one worker shape : Oracle Linux 7 . 

Regards

**Comment by brokedba** [comment]
Hi ,
I don't have access to your build code nor to your log . but you are correct the default terraform version in OCI devops runner is 1.2 , see [runtime_details ](https://docs.oracle.com/en-us/iaas/Content/devops/using/runtime_details.htm)

![image](https://github.com/brokedba/terraform-examples/assets/29458929/c2178491-1ea1-4e0d-ad74-4d963aa11136)


- However, what you seem to describe is similar to what I encountered when using terraform on cache in github action. 
you can try to overwrite the default terrafrm binary in the your path by runing  the below 

```  
 sudo cp ./terraform  /usr/local/bin/  
```
**Note**: Make sure your check the version after that
```     
terraform -v 
```  
Hope this helps.
Good luck
#CloudDude

**Comment by peppardo23** [comment]
I've tried to copy terraform directory under bin , but seems that at the path there is no folder with this name. Screenshot of the runner logs:
![image](https://github.com/brokedba/terraform-examples/assets/63729461/eb7aab3e-e1fb-42ba-acd7-c7650041bae9)
 However thanks for sharing official OCI docs with the expected runner versions, that's so useful. Because 1.2 is the OOTB version of the runner I will use it without any further installation.

**Comment by brokedba** [comment]
I'd use `which terraform` command to see where the terraform binary is located. but glad you found a solution.
